#!/usr/bin/env bash
#
# Author: Lilian Besson
# License: GPLv3
# Online: http://perso.crans.org/besson/bin/CP
# Online(2): https://bitbucket.org/lbesson/bin/src/master/CP
# Date: 21-07-2016
#
# A small wrapper around the output of the 'rsync' command, adding colors for interesting parts.
# Can be save to ~/bin/CP for example (or anywhere in your path).
#
# Perfect replacement for 'cp', notable improvement is the hability to copy to and from distant location (SSH, FTP etc).
#
version='.3'
LANG='en'

GREP="grep --color=always --line-buffered"
# GREP="grep --color=always"  # FIXME ?

echo -e "${reset}rsync: receiving the argument(s) $u${black}${@}${reset}"

# Change in the next line the default options for rsync
# and change in the next lines the colors (ANSI Colors, in GREP_COLOR) for separate parts of the output
(/usr/bin/rsync --ipv4 --verbose --times --perms --compress --human-readable --progress --archive "$@" 2>&1) \
 | $GREP -vP "^\s*((\[|\]|\(|\))\s*)+$" \
 | GREP_COLOR="37" $GREP -P "^[\.\-_0-9a-zA-Z/]+$|$" \
 | GREP_COLOR="4;01;32" $GREP -P "^(sending|sent|total).*|$" \
 | GREP_COLOR="01;33" $GREP -P "[\.0-9]+.B/s|$" \
 | GREP_COLOR="7;01;36" $GREP -P "^[ \t]*[\.0-9]+[KMGT]?|$" \
 | GREP_COLOR="01;35" $GREP -P "to.check=[0-9]+/[0-9]+|$" \
 | GREP_COLOR="01;30" $GREP -P "xfer#[0-9]+|$" \
 | GREP_COLOR="01;36" $GREP -P "[0-9]:[0-9][0-9]:[0-9][0-9]|$" \
 | GREP_COLOR="01;35" $GREP -P "^[0-9]+%|$" \
 | GREP_COLOR="7;01;34" $GREP -P "100%|$"