#! /usr/bin/env python3
# -*- coding: utf-8; mode: python -*-
""" Tiny Python 2/3 script to output a random number, like if your friend was telling it:

$ EtLaUnMecTeDit
Hmmm, 427736839403
$ EtLaUnMecTeDit
Hmmm, 427736839402

- *Date:* 14/06/2017
- *Author:* Lilian Besson, © 2017.
- *Licence:* MIT Licence (http://lbesson.mit-license.org).
"""

from __future__ import print_function  # Python 2 compatibility if needed

from random import randint

if __name__ == '__main__':
    print("Hmmm,", randint(10**10, 10**12))
