#!/usr/bin/env bash
content="$(w -h -s)"
# Subject: less than 16 characters are readable
subj="Login: $(w -h -s | grep -o "tty[1-7]" | head -n3) [PushToTel]"

DoForATime ()
{
    log=/tmp/DoForATime.log
    TIMEOUT=$1
    shift
    echo -e "Launching $@, in $PWD, for $TIMEOUT seconds only." >> "$log"
    "$@" >/dev/null 2>/dev/null & {
        sleep ${TIMEOUT};
        eval 'kill -9 $!' &>> "$log"
    }
}

DoForATime 8 mail_ghost.py "${content}" "$(echo $subj)"; notify-send "Jarvis Mail Daemon : newlogin" "${content}"  >/dev/null 2>/dev/null
