#!/usr/bin/env bash
content="$(df -h -l -t ext4 -t fuseblk)"
# Subject: less than 16 characters are readable
subj="df: $(echo "$content" | grep -o "[0-9][0-9]*% /[a-z/]*" | head -n3) [PushToTel]"

DoForATime ()
{
    log=/tmp/DoForATime.log
    TIMEOUT=$1
    shift
    echo -e "Launching $@, in $PWD, for $TIMEOUT seconds only." >> "$log"
    "$@" >/dev/null 2>/dev/null & {
        sleep ${TIMEOUT};
        eval 'kill -9 $!' &>> "$log"
    }
}

DoForATime 10 mail_ghost.py "${content}" "$(echo $subj)"; notify-send "Jarvis Mail Daemon : df" "${content}" >/dev/null 2>/dev/null

