#!/usr/bin/env bash
# Simple script to have a better OCaml prompt.
# (C) 2012-2014 Lilian Besson

rlwrap -t dumb --file="$HOME/keyword_mocaml_rlwrap.txt" --renice \
 --remember -Acm -aPassword: -pGreen \
 --break-chars "(){}[],+-=&^%\$#@\"" \
 --histsize 3000 -H mocaml_history.ml \
  ledit -x -u -h mocaml_history.ml \
   ocaml "$@"
