#!/usr/bin/env bash
#
# Script by Lilian Besson
# http://perso.crans.org/besson/

xtitle "(`date`<$USER@$HOSTNAME>:[`pwd`]> { Mutt 1.5.21 } : for crans.org"

clear

/usr/bin/mutt-patched -F ~/.mutt/muttrc.crans "$@" && clear

rm -vf yes