#!/usr/bin/env bash
# Simple Bash script to emulate octave-gui (available only after v4.0.0)
# (C) Lilian Besson, 2015
echo -e "Starting Octave GUI..."
notify-send "Octave" "Starting the Octave GUI..."

/usr/bin/octave --force-gui --silent --verbose --traditional --persist "$@" ;

notify-send "Octave" "Exiting the Octave GUI..."
echo -e "(done with the script $0)."
