#!/usr/bin/env bash

echo "[1;31mChangement de mot de passe pour $(whoami) sur $(hostname)[0m"
echo "Voici les règles à respecter pour que votre mot de passe soit valide:"
echo "[1;32mLe mot de passe doit faire au moins 9 caractères de longueur, il doit"
echo "contenir une majuscule, une minuscule et un chiffre, les autres"
echo "caractères réduisent la longueur minimale susmentionnée de 1.[0m"

echo "Ces règles sont celles sur zamok, elles peuvent être différentes ici."

echo "[1;33mVous devez d'abord fournir votre mot de passe actuel.[0m"
exec /usr/bin/passwd
