#!/usr/bin/env bash
# http://matt.might.net/articles/shell-scripts-for-passive-voice-weasel-words-duplicates/

weasels="many|various|very|fairly|several|extremely\
|exceedingly|quite|remarkably|few|surprisingly\
|mostly|largely|huge|large|tiny|((are|is) a number)\
|excellent|interestingly|significantly|basically\
|substantially|clearly|vast|relatively|completely\
|beaucoup|plein|vraiment|très|quelques|extrèmement\
|assez|surprenament|peu|remarquablement\
|principalement|grand|petit\
|intéressant|intéressante|significatif\
|clairement|relativement|complètement"

wordfile=""

# Check for an alternate weasel file
if [ -f "$HOME"/etc/words/weasels ]; then
    wordfile="$HOME/etc/words/weasels"
fi

if [ -f "$WORDSDIR"/weasels ]; then
    wordfile="$WORDSDIR/weasels"
fi

if [ -f words/weasels ]; then
    wordfile="words/weasels"
fi

if [ ! "$wordfile" = "" ]; then
    weasels="xyzabc123";
    for w in $(cat "$wordfile"); do
        weasels="$weasels|$w"
    done
fi


if [ "$1" = "" ]; then
    echo -e "Usage: $(basename "$0") <file> ..."
    exit
fi

egrep -H -i -n --color "\\b($weasels)\\b" "$@"
exit "$?"
