#!/bin/bash
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License version 2 for
# more details.
#
# You should have received a copy of the GNU General Public License version 2
# along with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

_vrun(){
  # declaration des variables locales
  local argc first cur opts files onoff playlist_opts help track

  #COMPREPLY désigne la réponse à renvoyer pour la complétion actuelle
  COMPREPLY=()

  # argc : vaut le nombre d'argument actuel sur la ligne de commande
  argc=${COMP_CWORD};

  # cur  : désigne la chaine de caractère actuelle pour le dernier mot de la ligne de commande
  first="${COMP_WORDS[1]}"
  cur="${COMP_WORDS[argc]}"
  if [ -f ~/.config/vrun/commandrc ]; then
    opts="`cat ~/.config/vrun/commandrc`"
  else
    opts="`vrun help \"\\*\" 2>/dev/null | sed 's/\. \. .*//;s/, /\n/g;/^+/d;s/| *//g;s/ .*//;s/\r//g'` start"
  fi
  files="add enqueue start"
  onoff="repeat loop random fullscreen f"
  playlist_opts="playlist goto delete"
  help="help longhelp ?"
  track="atrack vtrack vratio vcrop crop vzoom zoom vdeinterlace vdeinterlace_mode vdeinterlace_mode"

  # les options possibles pour notre auto-complétion
  if [ $argc -eq 1 ]; then
    # on auto-complete la ligne de commande en recherchant cur dans la liste opts.
    #A noter que le -- est important ici pour éviter les "injections d'options" depuis $cur.
    COMPREPLY=( $(compgen -W "$opts" -- $cur ) )
    return 0
  fi
  if [ $argc -eq 2 ]; then
    if [[ "$onoff" == *"$first"* ]]; then
      COMPREPLY=( $(compgen -W "on off" -- $cur) )
      return 0
    fi
    if [[ "$help" == *"$first"* ]]; then
	COMPREPLY=( $(compgen -W "$opts" -- $cur ) )
	return 0
    fi
    if [[ "$track" == *"$first"* ]]; then
      COMPREPLY=( $(compgen -W "`vrun $first |
        sed \"s/^\+.*//;
        s/| *//;
	s/\((\|\[\).*//;
	s/\( *\)$//;
	#s/ /_/g;
        s/ / /g; #on remplace les espace par un espace insécable dans le sed
        s/\r//g;
	s/'/\\\\\\\\'/;
	\"`" -- $cur ) )
    fi;
  fi
  if [[ "$first" = "delete" ]] || ([ $argc -le 3 ] && [[ "$first" = "move" ]]) || ([ $argc -eq 2 ] && [[ "$playlist_opts" == *"$first"* ]]); then
      COMPREPLY=( $(compgen -W "`vrun playlist 2 |
        sed \"s/^\+.*//;
        s/| *//;
	s/\((\|\[\).*//;
	s/\( *\)$//;
	#s/ /_/g;
        s/ / /g; #on remplace les espace par un espace insécable dans le sed
        s/\r//g;
	s/'/\\\\\\\\'/;
	\"` 2 - Liste de lecture" -- $cur ) )
      return 0
  fi
  if [[ "$files" == *"$first"* ]]; then
    _filedir &>/dev/null
    return 0
  fi

}

# On active l'auto-completion de la commande vrun en relation avec la fonction _vrun
complete -F _vrun vrun
